version: '3.4'

services:
  kafka:
    image: spotify/kafka
    hostname: kafka
    environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"
    command: >
      bash -c
      "(sleep 15s &&
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper
      localhost:2181 --replication-factor 1 --partitions 1
      --topic simple_topic &) && (supervisord -n)"
    networks:
      default:
        ipv4_address: 172.21.0.6

  inside.testtask.mc1:
    depends_on:
      - inside.testtask.mc2
      - jaeger
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=server=172.21.0.2;port=3306;database=EFCoreMySQL;user=root;password=my-secret-pw
      - WS:SocketMC2_URL=ws://172.21.0.4/api/WebSockets/ws
      - JaegerHost=172.21.0.7
    ports:
      - "5001:80"
    networks:
      default:
        ipv4_address: 172.21.0.3

  inside.testtask.mc2:
    depends_on:
      - kafka
      - jaeger
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KAFKA:server=kafka
      - JaegerHost=172.21.0.7
    ports:
      - "5000:80"
    networks:
      default:
        ipv4_address: 172.21.0.4

  inside.testtask.mc3:
    depends_on:
      - kafka
      - jaeger
      - inside.testtask.mc1
    command: dockerize -wait tcp://kafka:9092
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - KAFKA:server=kafka
      - MC1_url=http://172.21.0.3/
      - JaegerHost=172.21.0.7
    ports:
      - "5002:80"
    networks:
      default:
        ipv4_address: 172.21.0.5

  jaeger:
    image: jaegertracing/all-in-one:1.25
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      default:
        ipv4_address: 172.21.0.7

 

networks:
  default:
    external:
        name: test-insider
