// <auto-generated />
using System;
using Inside.TestTask.MC1.DomainModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inside.TestTask.MC1.Migrations
{
    [DbContext(typeof(MariaDbContext))]
    [Migration("20210816130639_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "6.0.0-preview.7.21378.4");

            modelBuilder.Entity("Inside.TestTask.MC1.DomainModel.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("End_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("MC1_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("MC2_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("MC3_timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Session_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Session_Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Inside.TestTask.MC1.DomainModel.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Inside.TestTask.MC1.DomainModel.Message", b =>
                {
                    b.HasOne("Inside.TestTask.MC1.DomainModel.Session", "Session")
                        .WithMany("Messages")
                        .HasForeignKey("Session_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Inside.TestTask.MC1.DomainModel.Session", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
